### ISSUE TITLE
Branch 7.3.x Reports as Unsupported release

### ISSUE THREAD

**Issue by webfaqtory** [tripal/tripal_analysis_go#15]
If this branch is ready for prime-time it will need a release on Drupal.org

**Comment by bradfordcondon** [comment]
closing as duplicate with #14 


@webfaqtory if you would like to install this module you can do so with git and drush


```

cd  my module directory# for example sites/all/modules/custom/
git clone https://github.com/tripal/tripal_analysis_go.git
cd tripal_analysis_go
git checkout 7.x-3.x
drush pm-enable -y tripal_analysis_go
```

**Comment by bradfordcondon** [comment]
on second thought, if youve already installed the v2 module via drush and are trying to upgrade to v3, the above commands wont work, if thats the case let me know

**Comment by webfaqtory** [comment]
I had V2 installed already and deleted the tripal_analysis_go directory. Then I cd to /sites/all/modules/tripal/legacy (this seemed an obvious place for the V3 version) and then installed via git clone and cleared cache. All seems to be well other than /admin/reports/updates reports 'Tripal GO Analysis 7.x-3.x' as 'Not supported!'. Presumably as there is no 7.x-3x release on https://www.drupal.org/project/tripal_analysis_go

**Comment by bradfordcondon** [comment]
OK great.  Until we make an official release that warning will persist, sorry about that!  I'll ping Stephen in the other issue and close this one as duplicate again.
